version: '3.8'  
services:

  server:
    image: twentycrm/twenty:${TAG:-latest}
    volumes:
      - server-local-data:/app/packages/twenty-server/.local-storage
    environment:
      - NODE_PORT=3000
      - NODE_ENV=production

      - PG_DATABASE_URL=postgres://${PG_DATABASE_USER:-postgres}:${PG_DATABASE_PASSWORD:-postgres}@${PG_DATABASE_HOST:-db-twenty}:${PG_DATABASE_PORT:-5432}/default
      - PG_DATABASE_USER=${PG_DATABASE_USER:-postgres}
      - PG_DATABASE_HOST=${PG_DATABASE_HOST:-db-twenty}
      - PG_DATABASE_PASSWORD=${PG_DATABASE_PASSWORD:-postgres}
      - PG_DATABASE_PORT=${PG_DATABASE_PORT:-5432}
      - SERVER_URL=${SERVER_URL:-https://twenty.biocentra.eu}
      - REDIS_URL=redis://redis-twenty:6379

      - STORAGE_TYPE=${STORAGE_TYPE:-local}
      - STORAGE_S3_REGION=${STORAGE_S3_REGION}
      - STORAGE_S3_NAME=${STORAGE_S3_NAME}
      - STORAGE_S3_ENDPOINT=${STORAGE_S3_ENDPOINT}

      - DISABLE_DB_MIGRATIONS=false
      - SIGN_IN_PREFILLED=false

      - APP_SECRET=${APP_SECRET:-hushhush}
      - MESSAGING_PROVIDER_GMAIL_ENABLED=${MESSAGING_PROVIDER_GMAIL_ENABLED}
      - CALENDAR_PROVIDER_GOOGLE_ENABLED=${CALENDAR_PROVIDER_GOOGLE_ENABLED}
      - AUTH_GOOGLE_CLIENT_ID=${AUTH_GOOGLE_CLIENT_ID}
      - AUTH_GOOGLE_CLIENT_SECRET=${AUTH_GOOGLE_CLIENT_SECRET}
      - AUTH_GOOGLE_CALLBACK_URL=${AUTH_GOOGLE_CALLBACK_URL}
      - AUTH_GOOGLE_APIS_CALLBACK_URL=${AUTH_GOOGLE_APIS_CALLBACK_URL}

    labels:
      - traefik.enable=true
      - 'traefik.http.routers.twenty.rule=Host("twenty.biocentra.eu")'
      - traefik.http.routers.twenty.entrypoints=https
      - traefik.http.routers.twenty.tls=true
      - traefik.http.routers.twenty.tls.certresolver=letsencrypt
      - traefik.http.services.twenty.loadbalancer.server.port=3000

    networks:
      - coolify-net
    healthcheck:
      test: ["CMD", "curl", "--fail", "http://localhost:3000/healthz"]
      interval: 5s
      timeout: 5s
      retries: 10
    restart: always

  worker:
    image: twentycrm/twenty:${TAG:-latest}
    volumes:
      - server-local-data:/app/packages/twenty-server/.local-storage
    command:
      - yarn
      - worker:prod
    environment:
      - PG_DATABASE_URL=postgres://${PG_DATABASE_USER:-postgres}:${PG_DATABASE_PASSWORD:-postgres}@${PG_DATABASE_HOST:-db-twenty}:${PG_DATABASE_PORT:-5432}/default
      - PG_DATABASE_USER=${PG_DATABASE_USER:-postgres}
      - PG_DATABASE_HOST=${PG_DATABASE_HOST:-db-twenty}
      - PG_DATABASE_PASSWORD=${PG_DATABASE_PASSWORD:-postgres}
      - PG_DATABASE_PORT=${PG_DATABASE_PORT:-5432}
      - SERVER_URL=${SERVER_URL:-https://twenty.biocentra.eu}
      - REDIS_URL=${REDIS_URL:-redis://redis-twenty:6379}
      - DISABLE_DB_MIGRATIONS=true # it already runs on the server
      - DISABLE_CRON_JOBS_REGISTRATION=true # it already runs on the server

      - STORAGE_TYPE=${STORAGE_TYPE:-local}
      - STORAGE_S3_REGION=${STORAGE_S3_REGION}
      - STORAGE_S3_NAME=${STORAGE_S3_NAME}
      - STORAGE_S3_ENDPOINT=${STORAGE_S3_ENDPOINT}
      
      - APP_SECRET=${APP_SECRET}
      - MESSAGING_PROVIDER_GMAIL_ENABLED=${MESSAGING_PROVIDER_GMAIL_ENABLED}
      - CALENDAR_PROVIDER_GOOGLE_ENABLED=${CALENDAR_PROVIDER_GOOGLE_ENABLED}
      - AUTH_GOOGLE_CLIENT_ID=${AUTH_GOOGLE_CLIENT_ID}
      - AUTH_GOOGLE_CLIENT_SECRET=${AUTH_GOOGLE_CLIENT_SECRET}
      - AUTH_GOOGLE_CALLBACK_URL=${AUTH_GOOGLE_CALLBACK_URL}
      - AUTH_GOOGLE_APIS_CALLBACK_URL=${AUTH_GOOGLE_APIS_CALLBACK_URL}
    networks:
      - coolify-net
    restart: always
    
  db-twenty:
    image: postgres:16
    volumes:
      - db-data:/var/lib/postgresql/data
    environment:
      - PG_DATABASE_USER=${PG_DATABASE_USER:-postgres}
      - PG_DATABASE_PASSWORD=${PG_DATABASE_PASSWORD:-postgres}
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "${PG_DATABASE_USER:-postgres}", "-h", "localhost", "-d", "postgres"]
      interval: 5s
      timeout: 5s
      retries: 10
    networks:
      - coolify-net
    restart: always

  redis-twenty:
    image: redis
    restart: always
    command: ["--maxmemory-policy", "noeviction"]
    networks:
      - coolify-net

volumes:
  db-data:
  server-local-data:

networks:
  coolify-net:
    external: true
