version: '3.8'
name: twenty
services:
  server:
    image: twentycrm/twenty:${TAG:-latest}
    volumes:
      - 'server-local-data:/app/packages/twenty-server/.local-storage'
    environment:
      - NODE_PORT=3000
      - PG_DATABASE_URL=postgres://${TWENTY_DB_USER}:${TWENTY_DB_PASS}@psql-twenty:5432/default
      - NODE_ENV=production

      - PG_DATABASE_USER=${TWENTY_DB_USER}
      - PG_DATABASE_HOSTNAME=psql-twenty
      - PG_DATABASE_PASSWORD=${TWENTY_DB_PASS}
      - PG_DATABASE_NAME=${TWENTY_DB}
      - PG_DATABASE_HOST=psql-twenty
      - PG_DATABASE_PORT=5432
      - SERVER_URL=${SERVER_URL:-https://twenty.biocentra.eu}
      - REDIS_URL=redis://redis:6379

      - STORAGE_TYPE=${STORAGE_TYPE}
      - STORAGE_S3_REGION=${STORAGE_S3_REGION}
      - STORAGE_S3_NAME=${STORAGE_S3_NAME}
      - STORAGE_S3_ENDPOINT=${STORAGE_S3_ENDPOINT}

      - APP_SECRET=${APP_SECRET}
      - DISABLE_DB_MIGRATIONS=false
      - SIGN_IN_PREFILLED=false

      # MESSAGING_PROVIDER_GMAIL_ENABLED: ${MESSAGING_PROVIDER_GMAIL_ENABLED}
      # CALENDAR_PROVIDER_GOOGLE_ENABLED: ${CALENDAR_PROVIDER_GOOGLE_ENABLED}
      # AUTH_GOOGLE_CLIENT_ID: ${AUTH_GOOGLE_CLIENT_ID}
      # AUTH_GOOGLE_CLIENT_SECRET: ${AUTH_GOOGLE_CLIENT_SECRET}
      # AUTH_GOOGLE_CALLBACK_URL: ${AUTH_GOOGLE_CALLBACK_URL}
      # AUTH_GOOGLE_APIS_CALLBACK_URL: ${AUTH_GOOGLE_APIS_CALLBACK_URL}

      # CALENDAR_PROVIDER_MICROSOFT_ENABLED: ${CALENDAR_PROVIDER_MICROSOFT_ENABLED}
      # MESSAGING_PROVIDER_MICROSOFT_ENABLED: ${MESSAGING_PROVIDER_MICROSOFT_ENABLED}
      # AUTH_MICROSOFT_ENABLED: ${AUTH_MICROSOFT_ENABLED}
      # AUTH_MICROSOFT_CLIENT_ID: ${AUTH_MICROSOFT_CLIENT_ID}
      # AUTH_MICROSOFT_CLIENT_SECRET: ${AUTH_MICROSOFT_CLIENT_SECRET}
      # AUTH_MICROSOFT_CALLBACK_URL: ${AUTH_MICROSOFT_CALLBACK_URL}
      # AUTH_MICROSOFT_APIS_CALLBACK_URL: ${AUTH_MICROSOFT_APIS_CALLBACK_URL}

      # EMAIL_FROM_ADDRESS: ${EMAIL_FROM_ADDRESS:-contact@yourdomain.com}
      # EMAIL_FROM_NAME: ${EMAIL_FROM_NAME:-"John from YourDomain"}
      # EMAIL_SYSTEM_ADDRESS: ${EMAIL_SYSTEM_ADDRESS:-system@yourdomain.com}
      # EMAIL_DRIVER: ${EMAIL_DRIVER:-smtp}
      # EMAIL_SMTP_HOST: ${EMAIL_SMTP_HOST:-smtp.gmail.com}
      # EMAIL_SMTP_PORT: ${EMAIL_SMTP_PORT:-465}
      # EMAIL_SMTP_USER: ${EMAIL_SMTP_USER:-}
      # EMAIL_SMTP_PASSWORD: ${EMAIL_SMTP_PASSWORD:-}

    labels:
      - traefik.enable=true
      - 'traefik.http.routers.twenty.rule=Host("twenty.biocentra.eu")'
      - traefik.http.routers.twenty.entrypoints=https
      - traefik.http.routers.twenty.tls=true
      - traefik.http.routers.twenty.tls.certresolver=letsencrypt
      - traefik.http.services.twenty.loadbalancer.server.port=3000

    networks:
      - coolify-net
    healthcheck:
      test: curl --fail http://localhost:3000/healthz 
      interval: 5s
      timeout: 5s
      retries: 10
    restart: always

  worker:
    image: twentycrm/twenty:${TAG:-latest}
    volumes:
      - server-local-data:/app/packages/twenty-server/.local-storage
    command:
      - yarn
      - worker:prod
    environment:
      - PG_DATABASE_URL=postgres://${TWENTY_DB_USER}:${TWENTY_DB_PASS}@psql-twenty:5432/default
      - PG_DATABASE_USER=${TWENTY_DB_USER}
      - PG_DATABASE_HOSTNAME=psql-twenty
      - PG_DATABASE_PASSWORD=${TWENTY_DB_PASS}
      - PG_DATABASE_NAME=${TWENTY_DB}
      - PG_DATABASE_HOST=psql-twenty
      - PG_DATABASE_PORT=5432
      - SERVER_URL=${SERVER_URL:-https://twenty.biocentra.eu}
      - REDIS_URL=redis://redis:6379
      - DISABLE_DB_MIGRATIONS=true

      - STORAGE_TYPE=${STORAGE_TYPE}
      - STORAGE_S3_REGION=${STORAGE_S3_REGION}
      - STORAGE_S3_NAME=${STORAGE_S3_NAME}
      - STORAGE_S3_ENDPOINT=${STORAGE_S3_ENDPOINT}
      
      - APP_SECRET=${APP_SECRET}
      # MESSAGING_PROVIDER_GMAIL_ENABLED: ${MESSAGING_PROVIDER_GMAIL_ENABLED}
      # CALENDAR_PROVIDER_GOOGLE_ENABLED: ${CALENDAR_PROVIDER_GOOGLE_ENABLED}
      # AUTH_GOOGLE_CLIENT_ID: ${AUTH_GOOGLE_CLIENT_ID}
      # AUTH_GOOGLE_CLIENT_SECRET: ${AUTH_GOOGLE_CLIENT_SECRET}
      # AUTH_GOOGLE_CALLBACK_URL: ${AUTH_GOOGLE_CALLBACK_URL}
      # AUTH_GOOGLE_APIS_CALLBACK_URL: ${AUTH_GOOGLE_APIS_CALLBACK_URL}

      # CALENDAR_PROVIDER_MICROSOFT_ENABLED: ${CALENDAR_PROVIDER_MICROSOFT_ENABLED}
      # MESSAGING_PROVIDER_MICROSOFT_ENABLED: ${MESSAGING_PROVIDER_MICROSOFT_ENABLED}
      # AUTH_MICROSOFT_ENABLED: ${AUTH_MICROSOFT_ENABLED}
      # AUTH_MICROSOFT_CLIENT_ID: ${AUTH_MICROSOFT_CLIENT_ID}
      # AUTH_MICROSOFT_CLIENT_SECRET: ${AUTH_MICROSOFT_CLIENT_SECRET}
      # AUTH_MICROSOFT_CALLBACK_URL: ${AUTH_MICROSOFT_CALLBACK_URL}
      # AUTH_MICROSOFT_APIS_CALLBACK_URL: ${AUTH_MICROSOFT_APIS_CALLBACK_URL}

      # EMAIL_FROM_ADDRESS: ${EMAIL_FROM_ADDRESS:-contact@yourdomain.com}
      # EMAIL_FROM_NAME: ${EMAIL_FROM_NAME:-"John from YourDomain"}
      # EMAIL_SYSTEM_ADDRESS: ${EMAIL_SYSTEM_ADDRESS:-system@yourdomain.com}
      # EMAIL_DRIVER: ${EMAIL_DRIVER:-smtp}
      # EMAIL_SMTP_HOST: ${EMAIL_SMTP_HOST:-smtp.gmail.com}
      # EMAIL_SMTP_PORT: ${EMAIL_SMTP_PORT:-465}
      # EMAIL_SMTP_USER: ${EMAIL_SMTP_USER:-}
      # EMAIL_SMTP_PASSWORD: ${EMAIL_SMTP_PASSWORD:-}
    depends_on:
      server:
        condition: service_healthy
      # redis:
      #   condition: service_healthy
    networks:
      - coolify-net
    restart: always

  # redis:
  #   image: redis:7
  #   restart: always
  #   command: ["--maxmemory-policy", "noeviction"]
  #   networks:
  #     - coolify-net
  #   healthcheck:
  #     test: ["CMD", "redis-cli", "ping"]
  #     interval: 5s
  #     timeout: 3s
  #     retries: 10

volumes:
  # docker-data:
  server-local-data:

networks:
  coolify-net:
    external: true









