
-- n8n
CREATE DATABASE n8n;
CREATE USER n8n_user WITH ENCRYPTED PASSWORD 'n8nBioCentra2025!!';
GRANT ALL PRIVILEGES ON DATABASE n8n TO n8n_user;
GRANT USAGE ON SCHEMA public TO n8n_user;
GRANT CREATE ON SCHEMA public TO n8n_user;
ALTER DEFAULT PRIVILEGES IN SCHEMA public GRANT ALL ON TABLES TO n8n_user;

-- calcom
CREATE USER calcom_user WITH ENCRYPTED PASSWORD 'calcomBioCentra2025!!';
CREATE DATABASE calcom WITH OWNER calcom_user;
GRANT ALL PRIVILEGES ON DATABASE calcom TO calcom_user;
GRANT USAGE ON SCHEMA public TO calcom_user;
GRANT CREATE ON SCHEMA public TO calcom_user;
ALTER DEFAULT PRIVILEGES IN SCHEMA public GRANT ALL ON TABLES TO calcom_user;

-- twenty (optional)
CREATE USER twenty_user WITH ENCRYPTED PASSWORD 'twentyBioCentra2025!!';
CREATE DATABASE twenty WITH OWNER twenty_user;
GRANT ALL PRIVILEGES ON DATABASE twenty TO twenty_user;
GRANT USAGE ON SCHEMA public TO twenty_user;
GRANT CREATE ON SCHEMA public TO twenty_user;
ALTER DEFAULT PRIVILEGES IN SCHEMA public GRANT ALL ON TABLES TO twenty_user;

-- plane
CREATE DATABASE plane;
CREATE USER plane_user WITH ENCRYPTED PASSWORD 'planeBioCentra2025!!';
GRANT ALL PRIVILEGES ON DATABASE plane TO plane_user;