-- n8n
CREATE DATABASE n8n;
CREATE USER n8n_user WITH ENCRYPTED PASSWORD 'n8nBioCentra2025!!';
GRANT ALL PRIVILEGES ON DATABASE n8n TO n8n_user;

-- calcom
CREATE DATABASE calcom;
CREATE USER calcom_user WITH ENCRYPTED PASSWORD 'calcomBioCentra2025!!';
GRANT ALL PRIVILEGES ON DATABASE calcom TO calcom_user;

-- twenty (optional)
CREATE DATABASE twenty;
CREATE USER twenty_user WITH ENCRYPTED PASSWORD 'twentyBioCentra2025!!';
GRANT ALL PRIVILEGES ON DATABASE twenty TO twenty_user;

-- plane
CREATE DATABASE plane;
CREATE USER plane_user WITH ENCRYPTED PASSWORD 'planeBioCentra2025!!';
GRANT ALL PRIVILEGES ON DATABASE plane TO plane_user;
