version: "3.8"

services:
  calcom:
    image: calcom.docker.scarf.sh/calcom/cal.com
    restart: always
    networks:
      - coolify-net
    environment:
      - NODE_ENV=production
      - TZ=Europe/Berlin
      - GENERIC_TIMEZONE=Europe/Berlin
      - NEXTAUTH_SECRET=${NEXTAUTH_SECRET}
      - CALENDSO_ENCRYPTION_KEY=${CALENDSO_ENCRYPTION_KEY}

      #email
      - EMAIL_FROM=schnack-schnick@gmx.de
      - EMAIL_FROM_NAME=Cal.com
      - EMAIL_DRIVER=smtp
      - EMAIL_SMTP_HOST=mail.gmx.net
      - EMAIL_SMTP_PORT=587
      - EMAIL_SMTP_USER=schnack-schnick@gmx.de
      - EMAIL_SMTP_PASSWORD=${EMAIL_SMTP_PASSWORD}

      - NEXT_PUBLIC_LICENSE_CONSENT=true
      - CALCOM_TELEMETRY_DISABLED=true

      - ALLOWED_HOSTNAMES=calcom.biocentra.eu
      - NEXT_PUBLIC_WEBAPP_URL=https://calcom.biocentra.eu
      - NEXT_PUBLIC_API_V2_URL=https://calcom.biocentra.eu/api/v2
      - CALCOM_HOST=calcom.biocentra.eu


      - CALCOM_DB=calcom
      - CALCOM_DB_USER=calcom_user
      - CALCOM_DB_PASS=${CALCOM_DB_PASS}
      - DATABASE_URL=postgresql://${CALCOM_DB_USER}:${CALCOM_DB_PASS}@postgresql:5432/${CALCOM_DB}
      - DATABASE_DIRECT_URL=postgresql://${CALCOM_DB_USER}:${CALCOM_DB_PASS}@postgresql:5432/${CALCOM_DB}
    ports:
      - 3000:3000
    labels:
      - traefik.enable=true
      - 'traefik.http.routers.calcom.rule=Host("calcom.biocentra.eu")'
      - traefik.http.routers.calcom.tls=true
      - traefik.http.routers.twenty.entrypoints=https
      - traefik.http.routers.calcom.tls.certresolver=letsencrypt
      - traefik.http.services.calcom.loadbalancer.server.port=3000
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:3000/ || exit 1"]
      interval: 10s
      timeout: 20s
      retries: 10

networks:
  coolify-net:
    external: true
