version: "3.8"


calcom:
    image: calcom.docker.scarf.sh/calcom/cal.com
    build:
      context: .
      dockerfile: Dockerfile
      args:
       
      network: stack
    restart: always
    networks:
      - stack
    ports:
      - 3000:3000
    env_file: .env
    environment:
      - DATABASE_URL=postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@${DATABASE_HOST}/${POSTGRES_DB}
      - DATABASE_DIRECT_URL=${DATABASE_URL}
    depends_on:
      - database
services:
  calcom:
    image: calcom.docker.scarf.sh/calcom/cal.com
    restart: always
    networks:
      - coolify-net
    environment:
      - NEXT_PUBLIC_WEBAPP_URL=${NEXT_PUBLIC_WEBAPP_URL}
      - NEXT_PUBLIC_API_V2_URL=${NEXT_PUBLIC_API_V2_URL}
      - NEXT_PUBLIC_LICENSE_CONSENT=${NEXT_PUBLIC_LICENSE_CONSENT}
      - CALCOM_TELEMETRY_DISABLED=${CALCOM_TELEMETRY_DISABLED}
      - NEXTAUTH_SECRET=${NEXTAUTH_SECRET}
      - CALENDSO_ENCRYPTION_KEY=${CALENDSO_ENCRYPTION_KEY}
      - DATABASE_URL=${DATABASE_URL}
      - DATABASE_DIRECT_URL=${DATABASE_URL}
      - NODE_ENV=production
      - TZ=Europe/Berlin
      - GENERIC_TIMEZONE=Europe/Berlin
      - NEXTAUTH_SECRET=${NEXTAUTH_SECRET}
      - CALENDSO_ENCRYPTION_KEY=${CALENDSO_ENCRYPTION_KEY}

      - EMAIL_FROM=schnack-schnick@gmx.de
      - EMAIL_FROM_NAME=Cal.com
      - EMAIL_DRIVER=smtp
      - EMAIL_SMTP_HOST=mail.gmx.net
      - EMAIL_SMTP_PORT=587
      - EMAIL_SMTP_USER=schnack-schnick@gmx.de
      - EMAIL_SMTP_PASSWORD=${EMAIL_SMTP_PASSWORD}
      - NEXT_PUBLIC_LICENSE_CONSENT=true
      - CALCOM_TELEMETRY_DISABLED=true # Disable telemetry which is the collection of anonymous usage data
      - NEXT_PUBLIC_WEBAPP_URL=https://calcom.biocentra.eu
      - NEXT_PUBLIC_API_V2_URL=https://calcom.biocentra.eu/api/v2
      - CALCOM_HOST=calcom.biocentra.eu


      - CALCOM_DB=default
      - CALCOM_DB_USER=admin
      - CALCOM_DB_PASS=${CALCOM_DB_PASS}
      - PG_DATABASE_USER=admin
      - PG_DATABASE_HOSTNAME=psql-calcom
      - PG_DATABASE_PASSWORD=${PG_DATABASE_PASSWORD}
      - PG_DATABASE_NAME=default
      - PG_DATABASE_HOST=psql-calcom
      - PG_DATABASE_PORT=5432
      - DATABASE_URL=postgres://${CALCOM_DB_USER}:${CALCOM_DB_PASS}@psql-calcom:5432/default
      - DATABASE_DIRECT_URL=postgres://${CALCOM_DB_USER}:${CALCOM_DB_PASS}@psql-calcom:5432/default
      - REDIS_URL=redis://redis:6379
    # ports:
    #   - 3000:3000
    labels:
      - traefik.enable=true
      - 'traefik.http.routers.calcom.rule=Host("calcom.biocentra.eu")'
      - traefik.http.routers.calcom.tls=true
      - traefik.http.routers.calcom.entrypoints=https
      - traefik.http.routers.calcom.tls.certresolver=letsencrypt
      - traefik.http.services.calcom.loadbalancer.server.port=3000
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:3000/ || exit 1"]
      interval: 10s
      timeout: 20s
      retries: 10

networks:
  coolify-net:
    external: true
